site_dir: /usr/local/nginx/docs/
site_name: CServer API Documentation
site_author: quadruple, igor725
site_url: https://docs.igvx.ru/
repo_url: https://github.com/igor725/cserver-lua-api

theme:
  features:
    - navigation.tabs
    - header.autohide
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - i18n:
      default_language: en
      material_alternate: true
      languages:
        en:
          name: English
          build: true
        ru:
          site_name: Документация по CServer API
          name: Russian
          build: true
